# This workflow will do a clean install of dependencies, build the source code, and deploy to GitHub Pages

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Generate OG images
      run: bun run scripts/generate-og-images.ts

    # - name: Generate README
    #   run: bun run scripts/generate-readme.ts

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
